version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "eventplanningdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
volumes:
  postgres:
    driver: local