
###
GET http://localhost:5142/Users/
Accept: application/json

###
POST http://localhost:5142/Users/login
Content-Type: application/json

{
  "email": "A",
  "password": "123"
}

###
POST http://localhost:5142/Users/register
Content-Type: application/json

{
  "name": "Test 1 ",
  "surname": "Test 1",
  "password": "123",
  "email": "A"
}

###
POST http://localhost:5142/Projects/create
Content-Type: application/json

{
  "projectName": "project9",
  "projectDescription": "Test 2"
}

###

POST http://localhost:5142/Projects/addUser
Content-Type: application/json

{
  "email": "john@example.com",
  "projectId": "43692b9c-c0e3-41d6-b597-39fd7e9fb6f6"
}


###
GET http://localhost:5142/Projects/43692b9c-c0e3-41d6-b597-39fd7e9fb6f6
Accept: application/json

###

GET http://localhost:5142/Users/projects
Accept: application/json


###
POST http://localhost:5142/Projects/setRole
Content-Type: application/json

{
  "userId": "f52d134c-62d7-4f47-b15a-f793d26e4e0e",
  "projectId":"5c824f90-e46c-4a31-92f4-2337bef8836c",
  "role": "Admin"
}


###
POST http://localhost:5142/Task/create
Content-Type: application/json

{
  "projectId": "43692b9c-c0e3-41d6-b597-39fd7e9fb6f6",
  "taskName": "Task 1"
}

###
GET http://localhost:5142/Task/cc9a92b9-2b77-44f6-9c60-a83f41990f56
Accept: application/json


###
POST http://localhost:5142/Task/AddUser
Content-Type: application/json

{
  "userId": "f52d134c-62d7-4f47-b15a-f793d26e4e0e",
  "taskId": "cc9a92b9-2b77-44f6-9c60-a83f41990f56"
}

###
POST http://localhost:5142/Guest/create
Content-Type: application/json

{
  "projectId": "2cc25a54-6e02-4143-9ed6-b2222f5b3c17",
  "guestName": "Danil",
  "guestSurname": "Tartilov"
}

###
GET http://localhost:5142/Projects/guests?projectId=2cc25a54-6e02-4143-9ed6-b2222f5b3c17
Accept: application/json

###
DELETE http://localhost:5142/Projects/590a1429-808d-4d14-be84-69a155fa76f2


###
DELETE http://localhost:5142/Task/3b3d6496-f911-4a64-a973-7aea2758643c


###
POST http://localhost:5142/Projects/Archive/43692b9c-c0e3-41d6-b597-39fd7e9fb6f6
Content-Type: application/json

###
POST http://localhost:5142/Projects/Unarchive/43692b9c-c0e3-41d6-b597-39fd7e9fb6f6
Content-Type: application/json

###
GET http://localhost:5142/Users/archivedProjects
Accept: application/json


###
PUT http://localhost:5142/Projects/deleteUser
Content-Type: application/json

{
  "email": "john@example.com",
  "projectId": "43692b9c-c0e3-41d6-b597-39fd7e9fb6f6"
}


###
DELETE http://localhost:5142/Users
