GET http://localhost:5142/Users/
Accept: application/json

###
POST http://localhost:5142/Users/login
Content-Type: application/json

{
  "email": "Anton@gmail.com",
  "password": "password123"
}

###
POST http://localhost:5142/Users/register
Content-Type: application/json

{
  "name": "Anton",
  "surname": "Vaicikevic",
  "password": "password123",
  "email": "Anton@gmail.com"
}

###
POST http://localhost:5142/Projects/create
Content-Type: application/json

{
  "projectName": "project7",
  "projectDescription": "Test 1"
}

###

POST http://localhost:5142/Projects/addUser
Content-Type: application/json

{
  "email": "john@example.com",
  "projectId": "5c824f90-e46c-4a31-92f4-2337bef8836c"
}


###
GET http://localhost:5142/Projects/8ecc0a57-b3ca-4cb9-8db7-415367583353
Accept: application/json

###

GET http://localhost:5142/Users/projects
Accept: application/json


###
POST http://localhost:5142/Projects/setRole
Content-Type: application/json

{
  "userId": "f52d134c-62d7-4f47-b15a-f793d26e4e0e",
  "projectId":"5c824f90-e46c-4a31-92f4-2337bef8836c",
  "role": "Admin"
}


###
POST http://localhost:5142/Task/create
Content-Type: application/json

{
  "projectId": "8ecc0a57-b3ca-4cb9-8db7-415367583353",
  "taskName": "Task 1"
}

###
GET http://localhost:5142/Task/cc9a92b9-2b77-44f6-9c60-a83f41990f56
Accept: application/json


###
POST http://localhost:5142/Task/AddUser
Content-Type: application/json

{
  "userId": "f52d134c-62d7-4f47-b15a-f793d26e4e0e",
  "taskId": "cc9a92b9-2b77-44f6-9c60-a83f41990f56"
}

###
POST http://localhost:5142/Guest/create
Content-Type: application/json

{
  "projectId": "8ecc0a57-b3ca-4cb9-8db7-415367583353",
  "guestName": "Danil",
  "guestSurname": "Tartilov"
}

###
GET http://localhost:5142/Projects/guests?projectId=8ecc0a57-b3ca-4cb9-8db7-415367583353
Accept: application/json
