name: .NET Build, Run and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker-compose build

    - name: Install Newman
      run: npm install -g newman

    - name: Start PostgreSQL and Apache containers
      run: docker-compose up -d

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run
      run: dotnet run --no-build &

    - name: Run Postman collection
      run: |
        newman run event-planning-back/Postman/Event_Planning_API_Test.postman_collection.json \
          --environment event-planning-back/Postman/EventPlanning.postman_environment.json \
          --reporters cli,junit \
          --reporter-junit-export newman-results.xml

    - name: Stop Docker containers
      run: docker-compose down
