name: Build and Run .NET Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker-compose build
      
    - name: Start PostgreSQL and Apache containers
      run: docker-compose up -d
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run
      run: dotnet run --no-build &
      
    - name: Wait for the application to be ready
      run: |
        echo "Waiting for the application to be ready..."
        sleep 30

    - name: Save process ID
      run: echo $! > app_pid.txt
      shell: bash
