name: .NET Build, Run and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker-compose build

    - name: Install Newman
      run: npm install -g newman

    - name: Start PostgreSQL and Apache containers
      run: docker-compose up -d

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    - uses: actions/setup-node@v2
      with: 
        node-version: "22"
    - name: "Install newman"
      run: "npm install -g newman"
    - name: "Install newman reporter"
      run: "npm install -g newman-reporter-htmlextra"
    
    - name: Build
      run: dotnet build --no-restore

    - name: Run
      run: dotnet run --no-build &

    - name: "Run tests"
      run: "newman run Postman/Event_Planning_API_Test.postman_collection.json -e Postman/EventPlanning.postman_environment.json -r htmlextra --reporter-htmlextra-export htmlreport.html --reporter-htmlextra-darkTheme  > runreport1.html"


    - name: Stop Docker containers
      run: docker-compose down
