name: .NET Build, Run and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker-compose build

    - name: Install Newman
      run: npm install -g newman

    - name: Start PostgreSQL and Apache containers
      run: docker-compose up -d

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - uses: actions/setup-node@v4
      with: 
        node-version: "22"
    - name: Install newman
      run: npm install -g newman
    
    - name: Install newman reporter
      run: npm install -g newman-reporter-htmlextra
      
    - name: Install dotnet-ef
      run: dotnet tool install --global dotnet-ef
    
    - name: Update database
      run: dotnet-ef database update
      
    - name: Build
      run: dotnet build --no-restore
    
    
      
   

    - name: Run
      run: dotnet run --no-build &
    
    - name: Wait for the application to be ready
      run: |
        echo "Waiting for the application to be ready..."
        sleep 10

    - name: Run Postman collection
      run: newman run Postman/Event_Planning_API_Test.postman_collection.json -e Postman/EventPlanning.postman_environment.json -r htmlextra --reporter-htmlextra-export Postman/htmlreport.html --reporter-htmlextra-darkTheme
    - name: Upload HTML report as artifact
    
    
    - uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: htmlreport.html

         
