name: Run Postman Tests

on:
  workflow_run:
    workflows: ["Build and Run .NET Application"]
    types:
      - completed

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Newman
      run: npm install -g newman
      
    - name: Run Postman collection
      run: |
        newman run path/to/your_collection.postman_collection.json \
          --environment path/to/your_environment.postman_environment.json \
          --reporters cli,junit \
          --reporter-junit-export newman-results.xml

    - name: Kill .NET application
      run: kill $(cat app_pid.txt)
      shell: bash
